export const ADD_CONTACTS="ADD_CONTACTS";
export const GET_CONTACTS="GET_CONTACTS";
export const GET_CONTACT="GET_CONTACT";
export const DELETE_CONTACTS="DELETE_CONTACTS";
export const UPDATE_CONTACT="UPDATE_CONTACT";